version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - cd api
      - npm install  # Assumes running inside the api directory
  build:
    commands:
      - echo Build started on `date`
      - npx tsc
post_build:
    commands:
      - echo Packaging files...
      - zip -r ../api-deployment-package.zip .  # Zip everything in the api directory
artifacts:
  files:
    - api-deployment-package.zip
  base-directory: 'api'  # Change to parent directory to include the zip
  discard-paths: yes