version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - cd api
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npx tsc
artifacts:
  files:
    - '**/*'
  base-directory: 'api'