version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - cd api  # Assuming this is where package.json and .ebextensions are located
      - npm install
  

  pre_build:
    commands:
      - echo "Preparing build..."
      - pwd  # Debug: Print current working directory
      - ls -al  # Debug: List all files in the current directory

  build:
    commands:
      - echo "Build started on `date`"
      - npx tsc  # Compile TypeScript

  post_build:
    commands:
      - echo "Packaging files..."
      - cd ..  # Step back to include .ebextensions in the zip
      - zip -r my-application.zip api  # Zip the entire api directory including .ebextensions

artifacts:
  files:
    - my-application.zip  # Specify the zip file as the artifact
  discard-paths: yes  # Since we are providing a path relative to the root