version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - cd api
      - npm install  # Installs dependencies within the api directory

  pre_build:
    commands:
      - echo "Transpiling TypeScript..."
      - npm run build  # Ensure this script exists in your package.json to compile TypeScript

  build:
    commands:
      - echo "Build completed on `date`"

  post_build:
    commands:
      - echo "Packaging files..."
      - zip -r ../api-deployment-package.zip .  # Package everything in the api directory, moving zip to the parent

artifacts:
  files:
    - api-deployment-package.zip
  discard-paths: yes